### Metadata request ###
GET http://localhost:4004/odata/v4/test/$metadata

### Get all from entity set ###
GET http://localhost:4004/odata/v4/test/Customer

### Get using filters ###
GET http://localhost:4004/odata/v4/test/Customer?$filter=CustomerName eq 'prova 1' or CustomerName eq 'prova 3'

### Get single by key ###
GET http://localhost:4004/odata/v4/test/Customer(577aa687-6671-4025-b2ba-f1e7ae767ea4)

### Create new entity ###
POST http://localhost:4004/odata/v4/test/Customer
Content-Type: application/json

{
    "CustomerName" : "CreationTest"
}