### Metadata request
GET http://localhost:4004/odata/v4/test/$metadata

### Create new entity   
# @name create
# @prompt customername the customer name sent in the request
POST http://localhost:4004/odata/v4/test/Customer
Content-Type: application/json

{
    "CustomerName" : "{{customername}}"
}

### Read all from entity set
GET http://localhost:4004/odata/v4/test/Customer

### Read using filters
GET http://localhost:4004/odata/v4/test/Customer?$filter=CustomerName eq 'prova 1' or CustomerName eq 'prova 3'

### Read single by key
GET http://localhost:4004/odata/v4/test/Customer({{create.response.body.ID}})


### Update with PATCH
PATCH  http://localhost:4004/odata/v4/test/Customer({{create.response.body.ID}})
Content-Type: application/json

{
    "CustomerName" : "UpdateTest"
}

### Update with PUT method
PUT  http://localhost:4004/odata/v4/test/Customer({{create.response.body.ID}})
Content-Type: application/json

{
    "CustomerName" : "UpdateTestPut"
}

### Delete entity
DELETE  http://localhost:4004/odata/v4/test/Customer({{create.response.body.ID}})